FROM postgres:16-alpine

# Adicione configurações personalizadas do PostgreSQL aqui, se necessário
# COPY postgresql.conf /etc/postgresql/postgresql.conf

# Exponha a porta padrão do PostgreSQL
EXPOSE 5432 
